### ISSUE TITLE
Something wrong with "/Chapter09/movieclassifier_with_update/update.py" ?

### ISSUE THREAD

**Issue by dongpohezui** [PacktPublishing/Python-Machine-Learning-Second-Edition#2]
When I run "/Chapter09/movieclassifier_with_update/update.py ",something is wrong.

After I deleted this line "from update import update_model", things seemed right.

What dose the line "from update import update_model" mean? Is it redundant?

**Comment by rasbt** [comment]
Hi there. Sorry for the late response, I wasn't aware that this GitHub repository exists. Regarding your question, yes, this line is redundant and can be safely removed. Good catch.
